### ISSUE TITLE
POST/PATCH resourceSpecification ignores "category" property

### ISSUE THREAD

**Issue by kostistr** [openslice/io.openslice.tmf.api#43]
URL: http://portal.openslice.io/tmf-api/resourceCatalogManagement/v4/resourceSpecification(/{id})
VERB: POST/(PATCH)
Payload: { ... , category: string, ... }

Response: 200 - { ..., category: null, ... }

**Comment by ctranoris** [comment]
fixed by merging branch crd
https://github.com/openslice/io.openslice.tmf.api/commit/65e7fe8d4ab68313d4413ad4d7be1a5cc0408435
